[project]
name = "fundeb"
version = "0.1.0"
description = """Trata-se de um projeto end-to-end de engenharia, ciência e análise de 
dados do Fundeb. Aqui você encontrará desde a extração e transformação dos dados 
brutos até a análise e visualização dos mesmos com geração automática de relatórios,
apresentações e dashboards."""
authors = [
    { name = "adrsb", email = "adrian.sbar07@gmail.com" },
]
license = { file = "LICENSE.txt" }
readme = "README.md"
requires-python = ">=3.13"
keywords = ["fundeb"]
dependencies = []


[project.urls]
# Homepage = "https://github.com/seu-usuario/seu-projeto"
# Documentation = "https://seu-usuario.github.io/seu-projeto"
Repository = "https://github.com/adrsb/fundeb.git"

# [project.scripts]
# meu-script = "fundeb.main:main"

[build-system]
requires = ["setuptools>=61.0"] # uv usa setuptools para construção por padrão
build-backend = "setuptools.build_meta"
